%% %CopyrightBegin%
%%
%% SPDX-License-Identifier: Apache-2.0
%%
%% SPDX-FileCopyrightText: Copyright 2015-2026 Rebar3 and its contributors
%%
%% SPDX-FileCopyrightText: Copyright 2026 Dipl. Phys. Peer Stritzinger GmbH
%%
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%%     http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.
%%
%% %CopyrightEnd%

-module(rebar_completion).

-export([generate/2]).

-type arg_type() :: atom | binary | boolean | float | integer | string.

-type cmpl_arg() :: #{short => char() | undefined,
                      long => string() | undefined,
                      type => arg_type(),
                      help => string()}.

-type cmpl_cmd() :: #{name := string(),
                      help := string() | undefined,
                      args := [cmpl_arg()],
                      cmds => [cmpl_cmd()]}.

-type cmpl_opts() :: #{aliases => [string()],
                       file => file:filename(),
                       %% TODO support fish and maybe some more shells
                       shell => bash | zsh}.
-export([prelude/1]).

-export_type([cmpl_opts/0, cmpl_cmd/0, cmpl_arg/0]).

-callback generate([cmpl_cmd()], cmpl_opts()) -> iolist().

-spec generate([cmpl_cmd()], cmpl_opts()) -> iolist().
generate(Commands, #{shell:=bash}=CmplOpts) ->
    rebar_completion_bash:generate(Commands,CmplOpts);
generate(Commands, #{shell:=zsh}=CmplOpts) ->
    rebar_completion_zsh:generate(Commands,CmplOpts).

prelude(#{shell:=Shell}) ->
    "# "++atom_to_list(Shell)++" completion file for rebar (autogenerated by rebar).\n".
