# %CopyrightBegin%
#
# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: Copyright 2015-2026 Rebar3 and its contributors
#
# SPDX-FileCopyrightText: Copyright 2026 Dipl. Phys. Peer Stritzinger GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%

name: Common Test

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'kickstarter/base'
      - 'kickstarter/stretch-1'

env:
  LATEST_OTP_RELEASE: 29

jobs:
  linux:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: ['29', '30.0-rc0']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0
    - name: Install Erlang
      uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124  # v1.24.1
      with:
        otp-version: ${{ matrix.otp_version }}
    - name: Compile
      run: ./bootstrap
    - name: CT tests
      run: ./rebar ct
    - shell: bash
      name: Dialyzer
      run: |
        ./rebar clean -a
        ./rebar as dialyzer dialyzer
      if: ${{ matrix.otp_version == env.LATEST_OTP_RELEASE }}

  macos:
    name: Test on MacOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0
    - name: Install Erlang
      uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124  # v1.24.1
      with:
        otp-version: ${{ env.LATEST_OTP_RELEASE }}
    - name: Compile
      run: ./bootstrap
    - name: CT tests
      run: ./rebar ct

  windows:
    name: Test on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0
    - name: Install Erlang
      uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124  # v1.24.1
      with:
        otp-version: ${{ env.LATEST_OTP_RELEASE }}
    - name: Compile
      run: .\bootstrap.ps1
    - name: CT tests
      run: .\rebar.ps1 ct
